### ISSUE TITLE
More documentation on how to use RunScript properly

### ISSUE THREAD

**Issue by t3hmrman** [sclevine/agouti#30]
Background: I'm trying to make sure a javascript-populated list on my page has the correct contents. I tried to check the HTML of the page by itself, but that doesn't update with the javascript changes...

So instead, I'm trying to pull information out of the javascript-heavy page and ensure that it contains what I expect, so I wrote code like this (replace 100 with something like window.App.getCount() for example):
```go
var number int
Expect(page.RunScript("return 100;", nil, &number)).To(Succeed())
Expect(number).To(Equal(100))
```

That didn't work however, and the RunScript fails with this error:
"failed to run script: request unsuccessful: error unreadable"

Am I using Agouti wrong (is it not meant to probe the running web driver instance)? I would have at least expecte dit to return the 100 as an integer.

**Comment by sclevine** [comment]
Hi @t3hmrman!

Did this solve your issue? If not, I'd be happy to help you figure out what's going on. If you happen to be on vacation, or busy with something else, I'm fine with leaving this open until you have time.

**Comment by t3hmrman** [comment]
hey @sclevine ,

Sorry I actually haven't worked on the project this code is in for a while. I will definitely get you some more feedback or close the ticket by this weekend (next few days). Thanks

**Comment by sclevine** [comment]
No worries at all! Take as much time as you need.

**Comment by t3hmrman** [comment]
Hey @sclevine here's some code that shows what I mean:

	Scenario("Finding the expected title on the index page", func() {
		Expect(page).To(HaveTitle("CasGo"))
		Eventually(func() string {
			var value string
			page.RunScript("return window.location;", nil, &value)
			return value
		}, 5*time.Second).Should(Equal(testHTTPServer.URL))
	
    })

What I get is this:

• Failure [5.227 seconds]
CasGo
/path/to/projects/go/src/github.com/sclevine/agouti/dsl/dsl.go:16
  Finding the expected title on the index page [It]
  /path/to/projects/go/src/github.com/sclevine/agouti/dsl/dsl.go:36

  Timed out after 5.000s.
  Expected
      <string>: 
  to equal
      <string>: http://127.0.0.1:38749

  /path/to/projets/go/src/github.com/t3hmrman/casgo/cas/integration_test/integration_test.go:40
------------------------------
SSSSSSS

Summarizing 1 Failure:

[Fail] CasGo [It] Finding the expected title on the index page 
/home/mrman/Programming/Projects/go/src/github.com/t3hmrman/casgo/cas/integration_test/integration_test.go:40

**Comment by t3hmrman** [comment]
I also think maybe I should add that I'm NOT running in OSX

**Comment by sclevine** [comment]
Can you post your setup as well? Specifically, the place where you call `page.Navigate`.

**Comment by t3hmrman** [comment]
Background(func() {
		page = CustomPage(Use().With("handlesAlerts"))
		page.Navigate(testHTTPServer.URL)
		page.Size(640, 480)
	})

	AfterEach(func() {
		page.Destroy()
	})

Oh and you can find the whole code here:

https://github.com/t3hmrman/casgo/blob/dev/cas/integration_test/integration_test.go

**Comment by sclevine** [comment]
I'm was able to replicate this on OS X. Hopefully I can get back to you to tonight with a fix!

**Comment by sclevine** [comment]
At first I thought you just needed `window.location.href` and an extra `/`:
```go
Scenario("Finding the expected title on the index page", func() {
    Expect(page).To(HaveTitle("CasGo"))
    Eventually(func() string {
        var value string
        page.RunScript("return window.location.href;", nil, &value)
        return value
    }, 5*time.Second).Should(Equal(testHTTPServer.URL + "/"))
})
```

But that didn't seem to do the trick. Turns out PhantomJS doesn't like receiving `{args: null}` for the `/session/:id/execute` endpoint. Should be fixed!

(PS: You can use the `HaveURL` matcher to check the current URL instead running `page.RunScript` with `window.location.href`.)

**Comment by t3hmrman** [comment]
Hey @sclevine, it's Fixed! :D :bow: 

Thanks a lot for your hard work and the fix! I am having a ball using Agouti (as you can probably see from the code, the agouti tests are doing a great job and only growing, as I fall down the testing rabbit hole). 

I added the window.location thing just to test with the latest master (earlier today) to make sure the problem wasn't fixed already. Will use `HaveUrl` when I need to check the URL for sure!
